# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0037_auto_20160316_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='chobi',
            field=models.ManyToManyField(blank=True, null=True, to='album.Chobi', verbose_name='\u099b\u09ac\u09bf'),
        ),
    ]
