# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0038_bandname_chobi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='shilpi',
            field=models.ManyToManyField(blank=True, null=True, to='album.Shilpi', verbose_name='\u09b6\u09bf\u09b2\u09cd\u09aa\u09c0'),
        ),
    ]
