# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0039_auto_20160328_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='ph_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u09ac\u09be\u0982\u09b2\u09bf\u09b6 \u09a8\u09be\u09ae'),
        ),
    ]
