# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0040_bandname_ph_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaan',
            name='title_alt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u09ac\u09be\u0982\u09b2\u09bf\u09b6'),
        ),
        migrations.AlterField(
            model_name='gaan',
            name='lyric',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u09ac\u09be\u0982\u09b2\u09bf\u09b6 \u0997\u09be\u09a8'),
        ),
    ]
